export type LangCode = "en" | "fr" | "es";

export interface Translations {
  // Email
  emailTitle: string;
  aiSummaryHeading: string;
  viralTweetsHeading: string;
  threadsHeading: string;
  viewOnX: string;
  readFullThread: string;
  moreInThread: (count: number) => string;
  threadLabel: string;
  tweetsAnalyzed: string;
  accountsFollowed: string;
  generatedBy: string;
  quietDayTitle: string;
  quietDayMessage: string;
  errorTitle: string;
  errorEncountered: string;
  stackTrace: string;
  errorSubjectPrefix: string;
  viralLabel: string;
  dateLocale: string;

  // Claude prompts
  systemPrompt: string;
  userPromptIntro: (date: string) => string;
  viralTweetsLabel: string;
  threadsLabel: string;
  produceAnalysis: string;
}

const en: Translations = {
  emailTitle: "X Morning Digest",
  aiSummaryHeading: "AI Summary",
  viralTweetsHeading: "Viral tweets",
  threadsHeading: "Threads",
  viewOnX: "View on X \u2192",
  readFullThread: "Read full thread \u2192",
  moreInThread: (count) => `+ ${count} more tweets in this thread`,
  threadLabel: "Thread",
  tweetsAnalyzed: "tweets analyzed",
  accountsFollowed: "accounts followed",
  generatedBy: "Generated by X Morning Digest",
  quietDayTitle: "Quiet day",
  quietDayMessage: "No viral content or notable threads detected in the analyzed period.",
  errorTitle: "X Digest - Error",
  errorEncountered: "The digest encountered an error:",
  stackTrace: "Stack trace:",
  errorSubjectPrefix: "X Digest \u2014 Error on",
  viralLabel: "viral",
  dateLocale: "en-US",

  systemPrompt: `You are a technology and strategy intelligence analyst.
You receive a selection of viral tweets and threads from influential tech accounts.

Your role is to produce a structured summary in English, clear and actionable.

Expected format:

## \ud83d\udd25 Today's Trends
- Topics dominating the conversation

## \ud83d\udce1 Weak Signals
- Less visible but potentially important information or opinions

## \ud83d\udca1 Key Takeaways
- Key insights, notable quotes or announcements not to be missed

Be concise, factual, and mention authors (@username) when relevant.
Do not repeat tweet content verbatim, synthesize.`,
  userPromptIntro: (date) => `Here is the Twitter digest data for ${date}:`,
  viralTweetsLabel: "Viral tweets",
  threadsLabel: "Threads",
  produceAnalysis: "Produce your structured analysis.",
};

const fr: Translations = {
  emailTitle: "X Morning Digest",
  aiSummaryHeading: "R\u00e9sum\u00e9 IA",
  viralTweetsHeading: "Tweets viraux",
  threadsHeading: "Threads",
  viewOnX: "Voir sur X \u2192",
  readFullThread: "Lire le thread complet \u2192",
  moreInThread: (count) => `+ ${count} autres tweets dans ce thread`,
  threadLabel: "Thread",
  tweetsAnalyzed: "tweets analys\u00e9s",
  accountsFollowed: "comptes suivis",
  generatedBy: "G\u00e9n\u00e9r\u00e9 par X Morning Digest",
  quietDayTitle: "Journ\u00e9e calme",
  quietDayMessage: "Aucun contenu viral ou thread notable d\u00e9tect\u00e9 dans la p\u00e9riode analys\u00e9e.",
  errorTitle: "X Digest - Erreur",
  errorEncountered: "Le digest a rencontr\u00e9 une erreur :",
  stackTrace: "Stack trace :",
  errorSubjectPrefix: "X Digest \u2014 Erreur le",
  viralLabel: "viraux",
  dateLocale: "fr-FR",

  systemPrompt: `Tu es un analyste de veille technologique et strat\u00e9gique.
Tu re\u00e7ois une s\u00e9lection de tweets viraux et de threads provenant de comptes influents de la tech.

Ton r\u00f4le est de produire un r\u00e9sum\u00e9 structur\u00e9 en fran\u00e7ais, clair et actionnable.

Format attendu :

## \ud83d\udd25 Tendances du jour
- Les sujets qui dominent la conversation

## \ud83d\udce1 Signaux faibles
- Les informations ou opinions moins visibles mais potentiellement importantes

## \ud83d\udca1 \u00c0 retenir
- Les insights cl\u00e9s, citations marquantes ou annonces \u00e0 ne pas manquer

Sois concis, factuel, et mentionne les auteurs (@username) quand c'est pertinent.
Ne r\u00e9p\u00e8te pas le contenu des tweets mot pour mot, synth\u00e9tise.`,
  userPromptIntro: (date) => `Voici les donn\u00e9es du digest Twitter du ${date} :`,
  viralTweetsLabel: "Tweets viraux",
  threadsLabel: "Threads",
  produceAnalysis: "Produis ton analyse structur\u00e9e.",
};

const es: Translations = {
  emailTitle: "X Morning Digest",
  aiSummaryHeading: "Resumen IA",
  viralTweetsHeading: "Tweets virales",
  threadsHeading: "Hilos",
  viewOnX: "Ver en X \u2192",
  readFullThread: "Leer hilo completo \u2192",
  moreInThread: (count) => `+ ${count} tweets m\u00e1s en este hilo`,
  threadLabel: "Hilo",
  tweetsAnalyzed: "tweets analizados",
  accountsFollowed: "cuentas seguidas",
  generatedBy: "Generado por X Morning Digest",
  quietDayTitle: "D\u00eda tranquilo",
  quietDayMessage: "No se detect\u00f3 contenido viral ni hilos notables en el per\u00edodo analizado.",
  errorTitle: "X Digest - Error",
  errorEncountered: "El digest encontr\u00f3 un error:",
  stackTrace: "Stack trace:",
  errorSubjectPrefix: "X Digest \u2014 Error el",
  viralLabel: "virales",
  dateLocale: "es-ES",

  systemPrompt: `Eres un analista de inteligencia tecnol\u00f3gica y estrat\u00e9gica.
Recibes una selecci\u00f3n de tweets virales e hilos de cuentas influyentes de tecnolog\u00eda.

Tu rol es producir un resumen estructurado en espa\u00f1ol, claro y accionable.

Formato esperado:

## \ud83d\udd25 Tendencias del d\u00eda
- Los temas que dominan la conversaci\u00f3n

## \ud83d\udce1 Se\u00f1ales d\u00e9biles
- Informaci\u00f3n u opiniones menos visibles pero potencialmente importantes

## \ud83d\udca1 Puntos clave
- Insights clave, citas destacadas o anuncios que no hay que perderse

S\u00e9 conciso, factual, y menciona a los autores (@username) cuando sea relevante.
No repitas el contenido de los tweets palabra por palabra, sintetiza.`,
  userPromptIntro: (date) => `Aqu\u00ed est\u00e1n los datos del digest de Twitter del ${date}:`,
  viralTweetsLabel: "Tweets virales",
  threadsLabel: "Hilos",
  produceAnalysis: "Produce tu an\u00e1lisis estructurado.",
};

const translations: Record<LangCode, Translations> = { en, fr, es };

export function getTranslations(lang: LangCode): Translations {
  return translations[lang];
}
